# Generated by Django 6.0.2 on 2026-02-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.CharField(default=None, max_length=512),
        ),
    ]
